# Site settings
title: Esquire's Blog
email: esquireatlarge@gmail.com
description: "The blog of the Esquire At Large"
baseurl: ""
url: "http://sguerri.com"
title_description: ""
title_image: "http://i.imgur.com/OWx6JeN.jpg"
google_analytics: "UA-20365477-4"
disqus_account: 
github_repository: https://github.com/esquireatlarge
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
# twitter_username: 
github_username:  esquireatlarge
#linkedin_link: http://
#google_plus_link: http://
#stackoverflow_link: http://

# Footer
#footer_left: "Theme: "<a href=\"http://carte-noire.jacobtomlinson.co.uk/">Carte-Noire</a>""
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
